if (NOT TARGET MyJsonCpp::MyJsonCpp)
    if (TARGET jsoncpp_static)
        add_library(MyJsonCpp::MyJsonCpp INTERFACE IMPORTED)
        set_target_properties(MyJsonCpp::MyJsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_static")
    elseif (TARGET jsoncpp_lib)
        add_library(MyJsonCpp::MyJsonCpp INTERFACE IMPORTED)
        set_target_properties(MyJsonCpp::MyJsonCpp PROPERTIES INTERFACE_LINK_LIBRARIES "jsoncpp_lib")
    endif ()
endif ()
